SELECT C.CAR_ID FROM CAR_RENTAL_COMPANY_CAR AS C 
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE LIKE '%세단%'
AND H.START_DATE LIKE '____-10%'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;